namespace OddsDashboard.Services;

public class ValidTeamsService
{
    private readonly HashSet<string> _validTeams = [
        "UConn Huskies",
        "Stetson Hatters",
        "Houston Cougars",
        "Longwood Lancers",
        "Purdue Boilermakers",
        "Montana St Bobcats",
        "Grambling St Tigers",
        "North Carolina Tar Heels",
        "Wagner Seahawks",
        "Howard Bison",
        "Iowa State Cyclones",
        "South Dakota St Jackrabbits",
        "Marquette Golden Eagles",
        "Western Kentucky Hilltoppers",
        "Tennessee Volunteers",
        "Saint Peter's Peacocks",
        "Arizona Wildcats",
        "Long Beach St 49ers",
        "Illinois Fighting Illini",
        "Morehead St Eagles",
        "Kentucky Wildcats",
        "Oakland Golden Grizzlies",
        "Creighton Bluejays",
        "Akron Zips",
        "Baylor Bears",
        "Colgate Raiders",
        "Auburn Tigers",
        "Yale Bulldogs",
        "Duke Blue Devils",
        "Vermont Catamounts",
        "Kansas Jayhawks",
        "Samford Bulldogs",
        "Alabama Crimson Tide",
        "Charleston Cougars",
        "San Diego St Aztecs",
        "UAB Blazers",
        "Wisconsin Badgers",
        "James Madison Dukes",
        "Gonzaga Bulldogs",
        "McNeese Cowboys",
        "Saint Mary's Gaels",
        "Grand Canyon Antelopes",
        "BYU Cougars",
        "Duquesne Dukes",
        "Texas Tech Red Raiders",
        "NC State Wolfpack",
        "South Carolina Gamecocks",
        "Oregon Ducks",
        "Clemson Tigers",
        "New Mexico Lobos",
        "Washington St Cougars",
        "Drake Bulldogs",
        "Florida Gators",
        "Boise State Broncos",
        "Colorado Buffaloes",
        "Texas Longhorns",
        "Virginia Cavaliers",
        "Colorado St Rams",
        "Dayton Flyers",
        "Nevada Wolf Pack",
        "Florida Atlantic Owls",
        "Northwestern Wildcats",
        "Nebraska Cornhuskers",
        "Texas A&M Aggies",
        "Utah State Aggies",
        "TCU Horned Frogs",
        "Mississippi St Bulldogs",
        "Michigan St Spartans"
    ];

    public bool IsTeamValid(string teamName) => _validTeams.Contains(teamName);
}